web:
  build: .
  volumes:
    - ".:/src"
  ports:
    - "3000:3000"
  command: nodemon -L bin/www

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes:
    - /www/public
  volumes_from:
    - web
  links:
    - web:web