version: '2'
services:
  db:
    image: mongo
    container_name: db
    restart: always
    volumes:
      - "/var/lib/mongodb:/var/lib/mongodb"
    ports:
      - 27017:27017
    command: "--smallfiles --logpath=/dev/null"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    restart: always
    volumes:
      - .:/home/app/desafio/
      - /home/app/desafio/node_modules
    ports:
      - 3000:3000
    links:
      - db:database
    command: node bin/www

  # nginx:
  #   container_name: nginx
  #   restart: always
  #   build: 
  #     context: ./nginx/
  #     dockerfile: Dockerfile
  #   ports:
  #     - 80:80
  #   volumes:
  #     - /www/public
  #   volumes_from:
  #     - web
  #   links:
  #     - web
